# Workflow to deploy and cleanup on merge
on: 
  pull_request:
    types: [closed]
    branches:
      - "qa"

jobs:
  deploy_qa:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    environment:
      name: QA

    env:
      ENV: "QA"
    
    steps:
    - uses: actions/checkout@v2

    - name: set env
      run: echo "ENV=$(echo $a | sed 's/-/_/g' <<< ${{ secrets.ENV }}_${GITHUB_HEAD_REF##*/})" >> $GITHUB_ENV

    - name: deploy
      run: echo "deploying to ${{ env.ENV }}"

    - name: cleanup
      run: echo "doing cleanup on ${{ env.ENV }}"
