# Workflow to compile and run when a pull request is created
on: 
  pull_request:
    types: [labeled]
    branches:
      - "qa"

jobs:
  build_qa:
    runs-on: ubuntu-20.04
    environment:
      name: QA

    env:
      ENV: "QA"
      
    steps:
    - uses: actions/checkout@v2
    
    - name: update apt repo
      run: apt-get update

    - name: remove old version of docker engine
      run: apt-get purge lxc-docker*

    - name: install new docker engine
      run: apt-get install docker-engine

    - name: docker build
      run: docker build -t finewine .

    - name: set env
      run: echo "ENV=$(echo $a | sed 's/-/_/g' <<< ${{ secrets.ENV }}_${GITHUB_HEAD_REF##*/})" >> $GITHUB_ENV

    - name: show env
      run: echo ${{ env.ENV }}


    - name: docker scan
      run: docker scan --file Dockerfile --exclude-base finewine --accept-license